  - name: Download the ova file
    get_url:
      url: "{{ download.ova }}"
      dest: "{{ helper_vm.workdir }}/downloads/{{ vcenter.template_name }}.ova"
      validate_certs: no
    environment:
      http_proxy: "{{ helper_vm.proxy_env }}"
      https_proxy: "{{ helper_vm.proxy_env }}"
    when: skip_download_ova is not defined
