
    - name: Unarchive oc client
      unarchive:
        remote_src: yes
        src: "{{ helper_vm.workdir }}/downloads/oc_client.tar.gz"
        dest: "{{ helper_vm.workdir }}/bin"
      # when: oc_client_download is changed

    - name: Unarchive openshift-install
      unarchive:
        remote_src: yes
        src: "{{ helper_vm.workdir }}/downloads/openshift_install.tar.gz"
        dest: "{{ helper_vm.workdir }}/bin"
      # when: openshift_install_download is changed

    - name: Put oc client to /usr/local/bin
      copy:
        remote_src: yes
        src: "{{ helper_vm.workdir }}/bin/oc"
        dest: /usr/local/bin
        mode: 0755

    - name: Put kubectl client to /usr/local/bin
      copy:
        remote_src: yes
        src: "{{ helper_vm.workdir }}/bin/kubectl"
        dest: /usr/local/bin
        mode: 0755

    - name: Put openshift-install cli to /usr/local/bin
      copy:
        remote_src: yes
        src: "{{ helper_vm.workdir }}/bin/openshift-install"
        dest: /usr/local/bin
        mode: 0755

    - name: Unarchive govc
      shell: gzip -dc "{{ helper_vm.workdir }}/downloads/govc.gz" > "{{ helper_vm.workdir }}/bin/govc"

    - name: Make govc executable
      file:
        path: "{{ helper_vm.workdir }}/bin/govc"
        mode: '775'
